### ISSUE TITLE
Sharing System Sound with Screensharing

### ISSUE THREAD

**Issue by rangerov** [miroslavpejic85/mirotalk#116]
### Feature request

It is %100 needed feature that we should we able to share the voice of certain app or tab or system sound while sharing screen.

**Comment by miroslavpejic85** [comment]
Done: https://github.com/miroslavpejic85/mirotalk/commit/e7bc5332e92c9f3d1c4e562009baebfbec1b880a

When you share a video from the screen sharing tab (es youtube video) it's audio will be played (not your voice), otherwise as usual, if you share the screen or slide or documents the participants will hear your voice. Remember also there is a video sharing option, in this case you can share any video, and both, your voice and the audio of the video, will be heard by the participants. 

Regards

**Comment by rangerov** [comment]
I see "Share system audio" right after your comment, thank you for bringing it.

**Comment by miroslavpejic85** [comment]
You are welcome.
