### ISSUE TITLE
not work on xiaomi

### ISSUE THREAD

**Issue by parsibox** [miroslavpejic85/mirotalk#122]
hi
dear on xiaomi google chrome application not ask for camera permissions
it work on samsung but not work on xiaomi
what can we do?

![image](https://user-images.githubusercontent.com/12513476/197479488-8130ceca-0e9c-4555-8a05-f3d8dc079ac7.png)

**Comment by miroslavpejic85** [comment]
Hello @parsibox, 

It could be that the default browser that xiaomi uses does not support the WebRTC MediaDevices.getUserMedia() API

You can check out the browser compatibility [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#browser_compatibility).

You can try to use chrome as [default browser](https://www.youtube.com/watch?v=_vTHFIMA2AI) instead of MI browser.

If you have pleasure, Join with us on [Discord](https://discord.gg/rgGYfeYW3N) too, for questions/discussions.

Thank you.
