### ISSUE TITLE
Disabling video does not block access to the webcam

### ISSUE THREAD

**Issue by l4rm4nd** [miroslavpejic85/mirotalk#152]
### Describe the bug

If a user decides to disable his video feed of the webcam, the webcam is still active or accessible by MiroTalk. This is a privacy issue, as the webcam should not be accessible as it was disabled by the user as an active choice. 

Also the status lights of webcams will continue to blink or breathe, which gives doubts about privacy.

### To Reproduce

1. Log into a web meeting with an enabled webcam
2. Disbable the web cam or video feed by hitting the respective button in the frontend
3. Although the video feed is not streamed anymore to participants, the webcam is still accessed and enabled in browser by MiroTalk. The status light, if available, blinks or breaths .. indicating a still ongoing access to the webcam.

### Expected behavior

If a user stops the webcam video, the webcam should not be accessed or be enabled anymore.

**Comment by miroslavpejic85** [comment]
This is because I currently `pause` the `video or audio stream` instead of turning it off altogether.

```js
stream.getVideoTracks()[0].enabled = false // or true
stream.getAudioTracks()[0].enabled = false // or true
```

To close the video-audio stream completely you should use instead

```js
stream.getTracks().forEach((track) => {
    track.stop();
});
```

**Comment by HariKrishna-28** [comment]
Hello! Can I work on this issue??

**Comment by miroslavpejic85** [comment]
Sure! Thank you.

**Comment by ketansaresa** [comment]
@miroslavpejic85 is this issue still un-assigned ?

**Comment by HariKrishna-28** [comment]
Hello @miroslavpejic85. I have started working on this issue. I will try to get it done within tomorrow.

**Comment by miroslavpejic85** [comment]
> Hello @miroslavpejic85. I have started working on this issue. I will try to get it done within tomorrow.

Of course! Take all the time you need; there's no rush at all. Thank you so much for the update! 😊

**Comment by ketansaresa** [comment]
Thanks for the heads up guys. @miroslavpejic85 @HariKrishna-28

**Comment by miroslavpejic85** [comment]
Hey @HariKrishna-28, 

Thank you for the contribution, it seems like you've found the right method to make the change but it's not enough.

The objective of this task entails managing the behavior of a webcam's indicator light when the "stop camera" button is pressed. The challenge is further complicated by the existence of two distinct video streams within the system. These streams are referred to as "initStream," which represents the initial video feed, and "localMediaStream," which is never deactivated but can be paused and resumed as needed. One of the primary concerns is that, due to the persistent activation of "localMediaStream," the LED indicator light in the room remains illuminated even when video transmission is halted.

To address this issue effectively, a more intricate and nuanced solution is required. The proposed solution should involve a mechanism for synchronizing the webcam's indicator light with the status of the active video streams. When the "stop camera" button is pressed, the indicator light should be turned off, signifying that video transmission has ceased. However, this action should be executed in a way that does not interfere with the availability of "localMediaStream" for potential reactivation.

In summary, the task demands approach to manage the webcam's indicator light behavior, ensuring it accurately reflects the status of video streaming while maintaining the readiness of "localMediaStream" for future use without keeping the LED light illuminated unnecessarily.

### To Reproduce

Steps to reproduce the behavior:

1. Log into a web meeting with an enabled webcam
2. Disbable the web cam or video feed by hitting the respective button in the frontend
3. Although the video feed is not streamed anymore to participants, the webcam is still accessed and enabled in browser by MiroTalk. The status light, if available, blinks or breaths .. indicating a still ongoing access to the webcam.

A quick fix can be:

```js
/**
 * Handle Video ON - OFF
 * @param {object} e event
 * @param {boolean} init on join room
 * @param {null|boolean} force video off (default null can be true/false)
 */
async function handleVideo(e, init, force = null) {
    if (!useVideo) return;
    // https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/getVideoTracks

    localMediaStream.getVideoTracks()[0].enabled =
        force != null ? force : !localMediaStream.getVideoTracks()[0].enabled;

    myVideoStatus = localMediaStream.getVideoTracks()[0].enabled;

    force != null
        ? (e.className = myVideoStatus ? className.videoOn : className.videoOff)
        : (e.target.className = myVideoStatus ? className.videoOn : className.videoOff);

    videoBtn.className = myVideoStatus ? className.videoOn : className.videoOff;

    if (init) {
        initVideoBtn.className = myVideoStatus ? className.videoOn : className.videoOff;
        setTippy(initVideoBtn, myVideoStatus ? 'Stop the video' : 'Start the video', 'top');
        initVideo.style.display = myVideoStatus ? 'block' : 'none';
        initVideoSelect.disabled = !myVideoStatus;
        lS.setInitConfig(lS.MEDIA_TYPE.video, myVideoStatus);

        if (!myVideoStatus || force) {
            // stop the init/local video track (camera led off)
            stopVideoTracks(initStream);
            stopVideoTracks(localMediaStream);
        } else {
            // resume the init video track (camera led on)
            await refreshLocalMedia();
            await changeInitCamera(initVideoSelect.value);
        }
    } else {
        if (!myVideoStatus || force) {
            // stop the init/video track (camera led off)
            stopVideoTracks(initStream);
            stopVideoTracks(localMediaStream);
        } else {
            // resume the video track (camera led on) 
            await setupLocalMedia();
            await refreshLocalMedia();
        }
    }

    setMyVideoStatus(myVideoStatus);
}

/**
 * Stop video track from MediaStream
 * @param {MediaStream} stream 
 */
function stopVideoTracks(stream) {
    stream.getTracks().forEach((track) => {
        if (track.kind === 'video') track.stop();
    });
}
```

You can try this changes, however, is required further testing to make sure everything is working well.

Thank you and have a great day!

**Comment by HariKrishna-28** [comment]
Hello! @miroslavpejic85, thank you the suggestions. I will make sure to implement them.
