### ISSUE TITLE
Local SVG avatars instead of external service

### ISSUE THREAD

**Issue by phpony** [miroslavpejic85/mirotalk#157]
### Feature request

There's no need to generate traffic to eu.ui-avatars.com host when all we need is just a circle image with 2 letters in it. Them can be easily generated with JS and than used as data:image/svg+xml uri's.

### Pros

Less requests, less traffic, more privacy.

### Additional context

Working example:

https://github.com/phpony/mirotalk/commit/68fe8e49996c452e839d45a58bba2db2d613aa17

**Comment by miroslavpejic85** [comment]
Hi @phpony!

Thanks a lot, I totally agree with you!
I did some refactoring and fixing in the code, I kept the color of the bg different depending on the peer name as before, instead of static gray, and some fix - improvements.
I am attaching the files, adjust your branch and align it with mine, if you like, send me a Pull request will be gladly accepted.
[avatar-refactoring.zip](https://github.com/miroslavpejic85/mirotalk/files/11209650/avatar-refactoring.zip)

**Comment by miroslavpejic85** [comment]
Done, Thank you @phpony!

**Comment by phpony** [comment]
Sorry, had no time to form a pull request. Thank you for implementing it!

**Comment by miroslavpejic85** [comment]
Don't worry, Thank to you [phpony](https://github.com/miroslavpejic85/mirotalk/commit/f2d70ee75da786e809f7b73b86eda62fec271e3c#diff-c3eb992fbaa0b603cd6f9ab34aff720e723fbedd4b64065482d463a9a892d7d5R2667)!
