### ISSUE TITLE
Implement user profile system for chat too

### ISSUE THREAD

**Issue by anshuman2166AppproDev** [miroslavpejic85/mirotalk#20]
It would be epic if we have profile system like we have when camera is off, In chat. Hope u look forward at it

**Comment by Jaideep25** [comment]
But don't u think that's tough? 🤔

**Comment by miroslavpejic85** [comment]
Hi @anshuman2166AppproDev
Could you explain better what do you mean by chat profile system. Thanks so much

**Comment by Jaideep25** [comment]
Hey @miroslavpejic85  you had made this profile pic typre thing when the video is off like this 
![image](https://user-images.githubusercontent.com/67269475/119217485-27f5ad80-baf8-11eb-9d81-1153fa1a9f18.png)

The same way is it possible to put in chat, instead of 
![image](https://user-images.githubusercontent.com/67269475/119217499-39d75080-baf8-11eb-94e5-d279d241bab7.png)
this and 
![image](https://user-images.githubusercontent.com/67269475/119217503-40fe5e80-baf8-11eb-88c8-1f1a309ad58b.png)
this, in the chat room
![image](https://user-images.githubusercontent.com/67269475/119217509-4c518a00-baf8-11eb-81b6-333a2254b804.png)

**Comment by miroslavpejic85** [comment]
Aha, I understand now 👍

**Comment by miroslavpejic85** [comment]
Hello @anshuman2166AppproDev 
I Implemented `set avatar chat image by the peer name`: https://github.com/miroslavpejic85/mirotalk/commit/4dd9243661513daa0dc6a95d2eaec2b852d3fccf 
I also inverted the messages, in the sense to the `left` you see the `messages you send`, to the `right` the `messages you receive` 😉
Let's me know if you like it?

**Comment by Jaideep25** [comment]
![image](https://user-images.githubusercontent.com/67269475/119221041-03570100-bb0b-11eb-9aaa-c3fcee03dc4f.png)
Wooooow it's so coool

**Comment by miroslavpejic85** [comment]
Also pushed this small fix: https://github.com/miroslavpejic85/mirotalk/commit/c4b8c58c7cb7560f1edd707d58c867fe77a9473d 
In the other chats I have seen that whoever `writes the message` is displayed on the `right side`, whoever `receives` it on the `left side`. So I turned back to old settings...

**Comment by miroslavpejic85** [comment]
In the other chats I have seen that whoever `writes the message` is displayed on the `right side`, 
whoever `receives` it on the `left side`. 
So I turned back to old settings...

**Comment by Jaideep25** [comment]
Oh okk.. Thanks for the info! 😊

**Comment by anshuman2166AppproDev** [comment]
Epiccc !!!? ❤️❤️ I m late coz I was doing some get stuff
