### ISSUE TITLE
new audio streams are not added to recording

### ISSUE THREAD

**Issue by mohan43u** [miroslavpejic85/mirotalk#200]
## Describe the bug

When we start recording, we have two people. while recording is going on, one more person join. We expect that the new person's audio is also gets recorded, but only audio from the people who were present during start of the recording gets recorded.

## To reproduce

1. Have two people start a recording
2. Ask someone new to join to the same room
3. the newly joined person's audio is not recorded

## Expected behavior

The newly joined person who joined after we start recording should also be captured

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Linux
 - Browser: Chromium
 - Version: 119

**Comment by miroslavpejic85** [comment]
Hello @mohan43u,

It appears that including additional audio streams during a recording is not feasible with the current design of the MediaRecorder API. 

Typically, the process involves stopping the ongoing recording, creating a new MediaRecorder instance with the updated set of audio streams, and then initiating a new recording. 

This limitation is inherent in the [MediaRecorder API's](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorde) structure.

For more in-depth discussions and collaborative problem-solving, I recommend using our community forum instead of opening issues here. 

You can join our [community forum](https://discord.gg/rgGYfeYW3N), where we can engage in collective discussions and address any concerns before proceeding. 

Thank you for your understanding.
