### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by EntityinArray** [miroslavpejic85/mirotalk#233]
# Feature request

Hello, thank you for working on this amazing project

I have some ideas on how to make UI more pleasant
- Remove popup 'flyout' sound effect
- Please stop using Google Translate on-the-fly translation of the UI, it does a horrible job. Support localization files and use a crowdsourced translation service
- Don't show 'Share the room' popup when user joins, it's annoying
- Make 'Invite others to join' show 'Share the room' window instead of triggering sharing function of the OS. It's really badly designed on Windows and frequently crashes.
![image](https://github.com/miroslavpejic85/mirotalk/assets/18554021/1dded00f-8957-4f52-afce-5949496570cb)
- Share file window is useless. Just instantly open the file open dialog when user clicks the Share file button. And even better, support drag and drop
![image](https://github.com/miroslavpejic85/mirotalk/assets/18554021/c3c12465-e609-44a4-9df0-5f8be121ff8d)
- As far as i can tell, this is a fork of Zipcall. Could you make the UI look more sleek like in this screenshot?
![image](https://github.com/miroslavpejic85/mirotalk/assets/18554021/23a69eca-011c-4c50-a2b5-e026fbeb53ea)

**Comment by miroslavpejic85** [comment]
Hello @EntityinArray,

I will answer you bellow:

> Hello, thank you for working on this amazing project

Thank you for your positive feedback. 

Next time, please use the [mirotalk-forum](https://discord.gg/rgGYfeYW3N) for any questions or discussions. This Github space is mainly for confirmed bugs. Thank you! 😊

Regarding your suggestions there is a channel in the forum `ideas and suggestions`, where we can discuss all tighter regarding as more of your requests are already there.

> Remove popup 'flyout' sound effect

![mirotalk-p2p-disable-sounds](https://github.com/miroslavpejic85/mirotalk/assets/70838434/2079f83b-591e-40b1-886c-76842f90ef3a)

> Please stop using Google Translate on-the-fly translation of the UI, it does a horrible job. Support localization files and use a crowdsourced translation service

We have chosen to use Google Translate to save time. In the future, we plan to implement a file translation system, though this will require more development time.

> Don't show 'Share the room' popup when user joins, it's annoying

![mirotalk-p2p-disable-share-room-popup](https://github.com/miroslavpejic85/mirotalk/assets/70838434/e4522ac4-f755-4830-b690-ba80ae2f9b68)

> Make 'Invite others to join' show 'Share the room' window instead of triggering sharing function of the OS. It's really badly designed on Windows and frequently crashes.

It appears that this issue is related to Windows rather than MiroTalk, as MiroTalk employs the same method, first try with [navigator.share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), across all operating systems and devices for sharing the room.

> Share file window is useless. Just instantly open the file open dialog when user clicks the Share file button. And even better, support drag and drop

![mirotalk-p2p-video-drag-and-drop](https://github.com/miroslavpejic85/mirotalk/assets/70838434/405d74ff-f7a0-4a08-a957-1ef25f52c8dc)

Maybe in the next release I can add the Drag and Drop feature to the window file sharing popup as well.

> As far as i can tell, this is a fork of Zipcall. Could you make the UI look more sleek like in this screenshot?

I initially used the HTML landing page template and later purchased the original license from the template's author, [Davide Pacilio](https://cruip.com/demos/neon/). You can find the link in the Readme Credits section. If you're seeking a user interface similar to the standard one-to-one video call, I recommend checking out the MiroTalk C2C project.

![mirotalk-c2c](https://github.com/miroslavpejic85/mirotalk/assets/70838434/66fd176c-1b5f-4f1e-a189-dbd1c96dd057)

If you have further ideas and suggestions, please join our community forum as mentioned earlier.

Cheers,
Miroslav

**Comment by miroslavpejic85** [comment]
`Drag and Drop` added in the widow file share as well

![mirotalk-p2p-file-drag-and-drop](https://github.com/miroslavpejic85/mirotalk/assets/70838434/21735c48-83eb-4904-aa20-d41f17a7d20f)
