### ISSUE TITLE
mirotalk.io

### ISSUE THREAD

**Issue by Garrett213** [miroslavpejic85/mirotalk#241]
# MiroTalk forum

If you have `ideas, suggestions, questions, doubts` about MiroTalk or `need support`, please use the MiroTalk Forum instead:

👉 [https://discord.gg/rgGYfeYW3N](https://discord.gg/rgGYfeYW3N)

Got asked to use this but url given was https://mirotalk.io 

Don't have time to investigate but suspect it is a malware site since there is no mention of it here or at mirotalk.com

**Comment by miroslavpejic85** [comment]
Hello @Garrett213,

Thank you for your report. Since this issue has occurred previously, we appreciate your vigilance. In the future, please contact me directly at miroslav.pejic.85@gmail.com or notify us privately through our forum. 

`We have reported this`

To prevent any further inappropriate visits to the mentioned site, which is unrelated to our official live demo, I am closing this thread. Thank you for your understanding.
