### ISSUE TITLE
About MiroTalk licence (AGPL)

### ISSUE THREAD

**Issue by alexe100** [miroslavpejic85/mirotalk#244]
Hi
I am looking for a self deploy SFU to be hosted in my servers and let Web apps, desktop apps and mobile apps to connect to it through iframe or using browsers or embedded browsers (e.g. WebView). I do not plan to change the mirotalk software and all the client apps will be for free use and download. Does I have to adhere to the AGPL in my client apps or can I choose any free/ permissive licence?

Thank you
Alex

**Comment by miroslavpejic85** [comment]
Hi Alexe100,

If you’re using Mirotalk, which is licensed under the Affero General Public License v3 (AGPLv3), and you are deploying it on your servers while allowing others to connect through web apps, desktop apps, or mobile apps, you must adhere to the AGPLv3 requirements for your server-side deployment.

The AGPLv3 stipulates that if you modify the software or use it to provide a service over a network, you must make the source code of your modifications available to users of the service. However, the license does not impose any requirements on the licensing of client-side apps that interact with the server.

So, while you must comply with AGPLv3 for the server-side code, you are free to choose any license for your client apps, whether it’s free, permissive, or otherwise. Just make sure to comply with AGPLv3 requirements for the server-side software itself.

As specified in the README, please use the community forum for any questions. For more information about the MiroTalk project’s licensing options, please visit: [Licensing Options](https://docs.mirotalk.com/license/licensing-options/)

Thank you.

**Comment by alexe100** [comment]
Very clear.
Thank you
