### ISSUE TITLE
Record entire meeting

### ISSUE THREAD

**Issue by Owned-by-Luce** [miroslavpejic85/mirotalk#38]
Is this possible to record entire meeting? such as screen sharing, every attendees video cam etc.

**Comment by Jaideep25** [comment]
Welcome @Owned-by-Luce 
Yep it's possible to record the entire meeting, attendees, video cam n everyting you can try it your self also!

**Comment by Owned-by-Luce** [comment]
Can u implement entire meeting recorder please?
Im just web site user.

**Comment by miroslavpejic85** [comment]
Hi @Owned-by-Luce, welcome! 
![image](https://user-images.githubusercontent.com/70838434/122385076-a5cc9d80-cf6c-11eb-98e5-9d3514085e9d.png)
For now, the `recording` is done on `your own video-audio stream due to privacy`. I could `extend` the recording function in the future to record also the `audio of other users in the room` as well, obviously warning them with a popup alert.

**Comment by Owned-by-Luce** [comment]
Okay thanks a lot

**Comment by miroslavpejic85** [comment]
U welcome!
