### ISSUE TITLE
Screenshare audio

### ISSUE THREAD

**Issue by Seishirou101** [miroslavpejic85/mirotalk#49]
Hello! I'm not sure the requesting format or if its possible but is there a way to share the audio of the screen/tab?

**Comment by miroslavpejic85** [comment]
Hi @Seishirou101, welcome!
When you `share your screen`,  the `participants` should be` able to hear audio` as well. Could you explain me better what you mean? Thanks so much.

**Comment by Jaideep25** [comment]
Hey @miroslavpejic85 , actually @Seishirou101  means that... when you screen share it doesnt show an option to share the audio, nor the audio gets shared... 
![image](https://user-images.githubusercontent.com/67269475/125033970-a957ce00-e0ad-11eb-9dcb-dc705f64a361.png)
the bottom corner it shows an audio check box if you want to share the audio or no...
Hope you understood! Thanks!

**Comment by miroslavpejic85** [comment]
Hey @Jaideep25 you mean this one?

<img width="610" alt="screen-share-audio" src="https://user-images.githubusercontent.com/70838434/125068509-d8723d80-e0b5-11eb-8086-54758b2ea581.png">

But not need, because if you not want to share the audio just click on the left audio button, it's valid for both camera & screen-sharing audio.

<img width="216" alt="audio-on-off" src="https://user-images.githubusercontent.com/70838434/125068644-fc358380-e0b5-11eb-8b3d-4c713f02ad75.png">

**Comment by Seishirou101** [comment]
Yes Jaideep25 was correct and I did not see a share audio button but did not know that the share audio button indeed shares the screen share as well! Which audio does it share? I'm assuming the default audio device the computer has as default? or is everything? I will have to test later. Thanks!

**Comment by miroslavpejic85** [comment]
To start or stop screen sharing, there is the button on the left for the purpose. 
For audio, there is a button to enable and disable it. 
As for what audio you are sharing, you see it from the settings

<img width="383" alt="audio" src="https://user-images.githubusercontent.com/70838434/125080716-6c97d100-e0c5-11eb-8edb-5538ae834b47.png">

**Comment by Seishirou101** [comment]
It looks like to share audio of the screenshare, I need to have the microphone set to the audio device the application is running on, but otherwise it works great! Thanks!
