### ISSUE TITLE
Privacy policy is missing

### ISSUE THREAD

**Issue by bryankaplan** [miroslavpejic85/mirotalk#5]
The demo server's website does not identify itself as a demo server, inviting the world to use this tool. Yet no mention is made of whether any (meta)data are retained, and if so what the sharing and retention policies are. A privacy policy would clarify for users whether the demo server can be relied upon, or whether self-hosting is preferable for privacy reasons.

**Comment by miroslavpejic85** [comment]
Hi bryankaplan, welcome again!
Aha you say that it would be necessary to add a Privacy policy part? 
All data, logs, etc. are currently not saved anywhere!
They are only processed by the signaling server: https://github.com/miroslavpejic85/mirotalk/blob/master/server.js in order to exchange info to establish peer to peer connections between the various browsers. And is deleted at all when mirotalk restarts, every 30 min., as i use free version service on heroku, to show the demo.

**Comment by miroslavpejic85** [comment]
I just use Google Analytics to track aggregated usage statistics in order to improve mirotalk.

**Comment by bryankaplan** [comment]
Cool. A privacy policy would be a great place to let users know.

**Comment by bryankaplan** [comment]
For an example of a privacy-friendly privacy policy, check out [DDG's](https://duckduckgo.com/privacy).

> We don't collect or share personal information.
> That's our privacy policy in a nutshell.

**Comment by anshuman2166AppproDev** [comment]
I am making that page and hope it will be ready

**Comment by miroslavpejic85** [comment]
Will be done, work in progress. 😉

**Comment by miroslavpejic85** [comment]
https://github.com/miroslavpejic85/mirotalk/commit/2be7fea8a743262d8dbbb33f58b656b5a528f887
