### ISSUE TITLE
Improve meeting view

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalk#60]
Mirotalk is a great platform for meeting but however the meeting room view is very simple please make it more attractive like zoom or Google meet

**Comment by Jaideep25** [comment]
Hey @Sanyam2007  welcome!
Which features do you suggest for making it attractive 👀?
Regards.

**Comment by Sanyam2007** [comment]
I want to say that can you make the meeting room design attractive like zoom currently it is very simple

**Comment by miroslavpejic85** [comment]
Hi @Sanyam2007 :)

The intent of `MiroTalk` is to be `different` from all the others, which basically follow the same logic-view. 
For example, most of MiroTalk's functionalities are `dynamic`, in the sense that you can move them with the mouse inside the screen (chat, whiteboard ...) and play with the themes.

The video view covers the entire area of the screen, in order to see the participants better, that with a click of the mouse you can also view them in full screen. 

The buttons are on the left, very comfortable in my opinion even in mobile devices. 

But I accept suggestions for further improvement :) As @Jaideep25  she said, what do you think you would change to make it better? I mean, give me a detailed list. 

Thanks to use MiroTalk. 
Regards

**Comment by Sanyam2007** [comment]
Ok but there is one more thing in my mind that we can not see how many participants are present in the meeting and all the participants list and who is the organizer only this feature is not available otherwise this is a
Awesome platform
