### ISSUE TITLE
Disable the form at the end of the call.

### ISSUE THREAD

**Issue by SrIzan10** [miroslavpejic85/mirotalk#97]
### Feature request

A way to disable the form at the end of the call.

### Pros

don't know what pros this could have

### Additional context

nothing.

**Comment by miroslavpejic85** [comment]
Hello @SrIzan10,
I use the survey form to collect information in order to improve the project. 
If you don't want to, just set the [surveyActive](https://github.com/miroslavpejic85/mirotalk/blob/master/public/js/client.js#L46) variable to false. 
```js
const surveyActive = false; // when leaving the room give a feedback
```
By doing so you will be redirected to the [newcall](https://github.com/miroslavpejic85/mirotalk/blob/master/public/js/client.js#L5333) page, that would: https://mirotalk.up.railway.app/newcall
Join with us on [discord](https://discord.gg/rgGYfeYW3N), in case you need help, support or discussion regarding.
Many thanks.
